Don't smash the docs with new copies by default.  Other minor changes.
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@8275 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/UserDoc/test b/UserDoc/test
--- a/UserDoc/test
+++ b/UserDoc/test
@@ -1,14 +1,28 @@
-THISSCRIPTDIR=`dirname $0`
+#!/bin/bash
+
+#Check the number of arguments supplied:
+if [ $# -ne 1 ]
+then
+    echo "test: ERROR: Must be given exactly one argument (the directory in which this script resides)."
+    exit 18 # Just a made-up error code.
+fi
+
+THISSCRIPTDIR=$1     #old: `dirname $0`
 
 #TODO Test other documentation formats besides PDF?
 
 pushd ${THISSCRIPTDIR}/sources > /dev/null
 make clean &> /dev/null
-make &> test.log
+LOG=${THISSCRIPTDIR}/test.log
+echo "Building documentation (see ${LOG})."
+make &> ${LOG}
 popd > /dev/null
-ls -l ${THISSCRIPTDIR}/SpecwareUserManual.pdf
-ls -l ${THISSCRIPTDIR}/SpecwareTutorial.pdf
-ls -l ${THISSCRIPTDIR}/SpecwareTransformationManual.pdf
-ls -l ${THISSCRIPTDIR}/SpecwareQuickReference.pdf
-ls -l ${THISSCRIPTDIR}/SpecwareLanguageManual.pdf
-ls -l ${THISSCRIPTDIR}/SpecwareIsabelleInterface.pdf
+
+#Check to ensure that the files got built:
+
+ls -l ${THISSCRIPTDIR}/sources/xform-manual/_build/latex/SpecwareTransformationManual.pdf
+ls -l ${THISSCRIPTDIR}/sources/tutorial/_build/latex/SpecwareTutorial.pdf
+ls -l ${THISSCRIPTDIR}/sources/user-manual/_build/latex/SpecwareUserManual.pdf
+ls -l ${THISSCRIPTDIR}/sources/isabelle-interface/_build/latex/SpecwareIsabelleInterface.pdf
+ls -l ${THISSCRIPTDIR}/sources/language-manual/_build/latex/SpecwareLanguageManual.pdf
+ls -l ${THISSCRIPTDIR}/sources/quick-reference/_build/latex/SpecwareQuickReference.pdf
