add flag that allows script to proceed even if sbcl is not present
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@4742 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Scripts/unix/Verify_SBCL b/Scripts/unix/Verify_SBCL
--- a/Scripts/unix/Verify_SBCL
+++ b/Scripts/unix/Verify_SBCL
@@ -18,9 +18,14 @@ for L in /usr/local/bin/sbcl "$HOME"/bin/sbcl /bin/lisp; do
   fi
 done
 
+
 if [ -z "$LISP" ]; then
   echo "  Verify_SBCL:  Could not find SBCL lisp"
-  exit 1
+  if [ "[$1]" != "[DONT-FAIL]" ]; then
+    echo "[$1] != [DONT-FAIL]"
+    sleep 10
+    exit 1
+  fi
 fi
 
 export BIG_LISP="$LISP --dynamic-space-size 880 --end-runtime-options"
@@ -70,3 +75,4 @@ echo "  Verify_SBCL:  BATCH_LISP           = [$BATCH_LISP]"
 echo "  Verify_SBCL:  BATCH_SPECWARE       = [$BATCH_SPECWARE]"
 echo "  Verify_SBCL:  BATCH_BOOTSTRAP      = [$BATCH_BOOTSTRAP]"
 echo "  "
+
