Added check for $SPECWARE4/Applications/Specware/lisp directory.
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@684 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/Specware/bin/linux/bootstrap b/Applications/Specware/bin/linux/bootstrap
--- a/Applications/Specware/bin/linux/bootstrap
+++ b/Applications/Specware/bin/linux/bootstrap
@@ -140,6 +140,12 @@ echo "\$SWPATH=$SWPATH"
 # handler is invoked. If, when bootrapping, the toplevel handler is
 # called, then we abort the bootstrap.
 
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/Specware/lisp is not a directory" 2>&1
+   exit 1
+fi
+
+
 if [   -f bin/linux/Specware4.dxl \
      -a \(   \( ! -f Specware4-base.lisp \) \
          -o bin/linux/Specware4.dxl -nt Specware4-base.lisp \) ]; then
@@ -184,6 +190,11 @@ else
 			    echo "Cvs saved lisp, Specware4-base.lisp, is newer than both lisp/Specware4.lisp."
 			fi
                         echo "Bootstrapping from cvs saved lisp: Specware4-base.lisp"
+			if [ ! -d lisp ]; then
+			    echo "mkdir lisp"
+			    mkdir lisp
+			fi
+
 			echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
 			cp -p -f Specware4-base.lisp lisp/Specware4.lisp
 			echo " "
diff --git a/Applications/Specware/bin/linux/build-image b/Applications/Specware/bin/linux/build-image
--- a/Applications/Specware/bin/linux/build-image
+++ b/Applications/Specware/bin/linux/build-image
@@ -64,6 +64,12 @@ cd "$SPECWARE4"/Applications/Specware
 
 export SWPATH; SWPATH="$SPECWARE4":.
 
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/Specware/lisp is not a directory" 2>&1
+   exit 1
+fi
+
+
 if [ ! -f lisp/Specware4.lisp -a ! -f Specware4-base.lisp ] ; then
    echo "Failed to $act: could not find $SPECWARE4/Applications/Specware/lisp/Specware4.lisp
    or $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
@@ -73,6 +79,11 @@ fi
 if [ ! -f lisp/Specware4.lisp ]; then
     echo "Could not find $SPECWARE4/Applications/Specware/lisp/Specware4.lisp,
     using cvs saved lisp, $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+    if [ ! -d lisp ]; then
+	echo "mkdir lisp"
+	mkdir lisp
+    fi
+    echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
     cp -p -f Specware4-base.lisp lisp/Specware4.lisp
 fi
 
@@ -80,6 +91,11 @@ if [ Specware4-base.lisp -nt lisp/Specware4.lisp ]; then
     echo "$SPECWARE4/Applications/Specware/lisp/Specware4.lisp is older than
     cvs saved lisp, $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
     echo "Using $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+    if [ ! -d lisp ]; then
+	echo "mkdir lisp"
+	mkdir lisp
+    fi
+    echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
     cp -p -f Specware4-base.lisp lisp/Specware4.lisp
 fi
 
