complain and exit on error
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@1627 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/Specware/bin/linux/build-cmulisp-image-for-release b/Applications/Specware/bin/linux/build-cmulisp-image-for-release
--- a/Applications/Specware/bin/linux/build-cmulisp-image-for-release
+++ b/Applications/Specware/bin/linux/build-cmulisp-image-for-release
@@ -135,7 +135,12 @@ $LISP <<-XXXX
 
 	(ext:save-lisp "$SPECWARE4/Applications/Specware/bin/linux/Specware4.cmuimage")
 XXXX
-
+# If the load failed (non-zero exit status) then we abort.
+if [ $RC -ne 0 ]; then
+  echo ""
+  echo "Building specware release using cmulisp failed with code $RC, exiting ..."
+  exit $RC
+fi
 
 # Now, build the rest of the directory tree.
 
