Add compatibility SPECWARE_INIT_FORM setting
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@4919 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/Specware/bin/linux/Specware-sbcl b/Applications/Specware/bin/linux/Specware-sbcl
--- a/Applications/Specware/bin/linux/Specware-sbcl
+++ b/Applications/Specware/bin/linux/Specware-sbcl
@@ -74,11 +74,41 @@ if [ -z "$SWPATH" ]; then
   SWPATH="/"
 fi
 
-export LISP_EXECUTABLE="$SPECWARE_BIN"/Specware4.sbclexe
-export LISP_DIRECTORY="$SPECWARE4"/
+# Try to find lisp executable:
 
-$xemacs -geometry =150x60+20+20 \
-	-title "Specware" \
-	-name "Specware" \
-	-l "$SPECWARE4"/Library/IO/Emacs/load-slime \
-        -f run-specware4 &
+if [ -z "$LISP" ]; then
+   for L in /Applications/sbcl/bin/sbcl /usr/local/bin/sbcl "$HOME"/bin/sbcl /bin/lisp; do
+      if [ -x "$L" ]; then
+         LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
+
+if [ -z "$SPECWARE_INIT_FORM" ]; then
+   SPECWARE_INIT_FORM=NIL
+   export SPECWARE_INIT_FORM
+fi
+
+LISP_DIR=`dirname "$LISP"`
+LISP_EXECUTABLE="$SPECWARE_BIN"/Specware4.sbclexe
+LISP_HEAP_IMAGE=NONE
+LISP_DIRECTORY="$SPECWARE4"/
+export LISP_EXECUTABLE
+export LISP_HEAP_IMAGE
+export LISP_DIRECTORY
+
+$xemacs -l "$SPECWARE4"/Library/IO/Emacs/load-slime \
+       -f run-specware4 &
+#       -name "Specware" \
+#       -title "Specware" \
+#       -geometry =150x60+20+20 \
