Updated Specware lisp load file to make it more easily changed for language extensions. Corrected Specware bootstrap to omit redundant checks in script and incorrect environment variable.
Update PSL files to agree with Specware files.


git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@716 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/PSL/bin/linux/bootstrap b/Applications/PSL/bin/linux/bootstrap
--- a/Applications/PSL/bin/linux/bootstrap
+++ b/Applications/PSL/bin/linux/bootstrap
@@ -1,64 +1,79 @@
 #!/bin/bash --noprofile
 
-# This script bootstraps Specware4.
-# That is,
-#  - it saves the old generated Specware4.lisp and Specware4.dxl (ie world)
-#  - it starts Specware4 
-#      - it first tries to run a lisp session with an existing dxl image
-#      - if that fails it tries to load Specware from previously generated lisp
-#  - applies Specware to itself (sw "/Applications/Specware/Specware4")
-#     to generate a new Specware4.lisp,
-#  - starts a fresh lisp session
-#  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
-#    (this compiles everything)
-#  - starts a fresh lisp session again
-#  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
-#  - dumps a world into the bin directory
-
-# Perhaps there should be a different script for bootstrapping from lisp
-# (bootstrap-from-lisp?).
+# This script bootstraps PSL.
 
 # The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
 # files. See "man bash" for details. The 'set -v' turns on echoing of
 # lines read. This will be removed later.
 
-# set -v
-
-# We assume SPECWARE4 has been set.
-if [ -z $SPECWARE4 ]; then
-    echo "Failed to bootstrap, SPECWARE4 environment variable not set"
-    exit 1
-fi
-
-echo \$SPECWARE4=$SPECWARE4
+act='bootstrap'
 
 PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin
 
-LISP=${LISP:-/usr/local/acl/acl61/alisp}
+# set -v
 
-if [ ! -f $SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl ]; then
-  echo "No Specware4.dxl"
-  exit 1
+# Test whether SPECWARE4 has been set
+if [ -z "$SPECWARE4" ]; then
+    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
+    exit 1
+fi
+
+# Test whether SPECWARE4 is a directory
+if [ ! -d "$SPECWARE4" ]; then
+   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
+   exit 1
+fi
+
+# Ensure SPECWARE4 is set to full pathname:
+case "$SPECWARE4" in
+    /*) : ok;;
+    *)  SPECWARE="`pwd`/$SPECWARE4";;
+esac
+
+if [ ! -d "$SPECWARE4"/Applications/PSL ]; then
+   echo "Failed to $act: could not find directory
+   $SPECWARE4/Applications/PSL" 2>&1
+   exit 1
 fi
 
 echo cd $SPECWARE4/Applications/PSL
 cd $SPECWARE4/Applications/PSL
 
+# Try to find lisp executable:
+
+if [ -z "$LISP" ]; then
+   for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp; do
+      if [ -x "$L" ]; then
+         export LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
+
 echo " "
-if [ -f lisp/PSL.lisp ]; then
-  echo "Saving previous PSL.lisp file ..."
-  echo "cp -f lisp/PSL.lisp lisp/PSL-save.lisp"
-  cp -f lisp/PSL.lisp lisp/PSL-save.lisp
+if [ -f lisp/Specware4.lisp ]; then
+  echo "Saving previous specware lisp file ..."
+  echo "cp -p -f lisp/Specware4.lisp lisp/Specware4-save.lisp"
+  cp -p -f lisp/Specware4.lisp lisp/Specware4-save.lisp
 else
-  echo "Note: No previous PSL lisp file."
+  echo "Note: No previous specware lisp file."
 fi
 echo " "
-if [ -f bin/linux/PSL.dxl ]; then
-  echo "Saving previous PSL image ..."
-  echo "cp -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl"
-  cp -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl
+if [ -f bin/linux/Specware4.dxl ]; then
+  echo "Saving previous specware image ..."
+  echo "cp -p -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl"
+  cp -p -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl
 else
-  echo "Note: No previous PSL image."
+  echo "Note: No previous specware image."
 fi
 echo " "
 
@@ -70,8 +85,10 @@ echo " "
 # Is there a way to inhibit all the warnings (eg unused variable)
 # when Lisp loads?
 
-SWPATH=$SPECWARE4:.
+export SWPATH=$SPECWARE4:.
 EXIT_ON_ERRORS=$SPECWARE4/Applications/Specware/bin/linux/exit-on-errors
+
+echo "\$SWPATH=$SWPATH"
 
 # All the toplevel routines that activate Specware return a boolean value.
 # They return true if the call to Specware succeeded without activating
@@ -79,22 +96,26 @@ EXIT_ON_ERRORS=$SPECWARE4/Applications/Specware/bin/linux/exit-on-errors
 # handler is invoked. If, when bootrapping, the toplevel handler is
 # called, then we abort the bootstrap.
 
-echo "Bootstrapping from existing Specware image: bin/linux/Specware4.dxl"
-echo " "
-cd $SPECWARE4/Applications/Specware
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/PSL/lisp is not a directory" 2>&1
+   exit 1
+fi
+
 bin/linux/Specware4-text -batch <<-XXXX
-	(load "$EXIT_ON_ERRORS")
-	(enlarge-stack 50000000)
+               :swpath
+	(load "$EXIT_ON_ERRORS") ; bin/linux/exit-on-errors
+	(enlarge-stack)
 	(exiting-on-errors 
 	  (if (sw "/Applications/PSL/PSL")
 	    (exit 0)
 	    (exit 1)))
-	XXXX
+XXXX
 RC=$?
+
 # If the bootstrap failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "Bootstrap of PSL failed with code $RC, exiting ..."
+  echo "Bootstrap failed with code $RC, exiting ..."
   exit $RC
 fi
 
@@ -121,7 +142,7 @@ RC=$?
 # If the load failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "First load of PSL failed with code $RC, exiting ..."
+  echo "First load failed with code $RC, exiting ..."
   exit $RC
 fi
 
@@ -141,13 +162,13 @@ $LISP -batch <<-XXXX
 	(load "$EXIT_ON_ERRORS")
 	(exiting-on-errors 
 	  (load "PSL.lisp"))
-	(excl::dumplisp :name "$SPECWARE4/Applications/PSL/bin/linux/PSL.dxl")
+	(excl::dumplisp :name "$SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl")
 XXXX
 RC=$?
 
 # If the load failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "Second load of PSL failed with code $RC, exiting ..."
+  echo "Second load failed with code $RC, exiting ..."
   exit $RC
 fi
