no message
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/branches/avendor@1504 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/PSL/bin/linux/bootstrap b/Applications/PSL/bin/linux/bootstrap
--- a/Applications/PSL/bin/linux/bootstrap
+++ b/Applications/PSL/bin/linux/bootstrap
@@ -1,64 +1,79 @@
 #!/bin/bash --noprofile
 
-# This script bootstraps Specware4.
-# That is,
-#  - it saves the old generated Specware4.lisp and Specware4.dxl (ie world)
-#  - it starts Specware4 
-#      - it first tries to run a lisp session with an existing dxl image
-#      - if that fails it tries to load Specware from previously generated lisp
-#  - applies Specware to itself (sw "/Applications/Specware/Specware4")
-#     to generate a new Specware4.lisp,
-#  - starts a fresh lisp session
-#  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
-#    (this compiles everything)
-#  - starts a fresh lisp session again
-#  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
-#  - dumps a world into the bin directory
-
-# Perhaps there should be a different script for bootstrapping from lisp
-# (bootstrap-from-lisp?).
+# This script bootstraps PSL.
 
 # The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
 # files. See "man bash" for details. The 'set -v' turns on echoing of
 # lines read. This will be removed later.
 
-# set -v
-
-# We assume SPECWARE4 has been set.
-if [ -z $SPECWARE4 ]; then
-    echo "Failed to bootstrap, SPECWARE4 environment variable not set"
-    exit 1
-fi
-
-echo \$SPECWARE4=$SPECWARE4
+act='bootstrap'
 
 PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin
 
-LISP=${LISP:-/usr/local/acl/acl61/alisp}
+# set -v
 
-if [ ! -f $SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl ]; then
-  echo "No Specware4.dxl"
-  exit 1
+# Test whether SPECWARE4 has been set
+if [ -z "$SPECWARE4" ]; then
+    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
+    exit 1
+fi
+
+# Test whether SPECWARE4 is a directory
+if [ ! -d "$SPECWARE4" ]; then
+   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
+   exit 1
+fi
+
+# Ensure SPECWARE4 is set to full pathname:
+case "$SPECWARE4" in
+    /*) : ok;;
+    *)  SPECWARE="`pwd`/$SPECWARE4";;
+esac
+
+if [ ! -d "$SPECWARE4"/Applications/PSL ]; then
+   echo "Failed to $act: could not find directory
+   $SPECWARE4/Applications/PSL" 2>&1
+   exit 1
 fi
 
 echo cd $SPECWARE4/Applications/PSL
 cd $SPECWARE4/Applications/PSL
 
+# Try to find lisp executable:
+
+if [ -z "$LISP" ]; then
+   for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp; do
+      if [ -x "$L" ]; then
+         export LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
+
 echo " "
 if [ -f lisp/PSL.lisp ]; then
-  echo "Saving previous PSL.lisp file ..."
-  echo "cp -f lisp/PSL.lisp lisp/PSL-save.lisp"
-  cp -f lisp/PSL.lisp lisp/PSL-save.lisp
+  echo "Saving previous specware lisp file ..."
+  echo "cp -p -f lisp/PSL.lisp lisp/PSL-save.lisp"
+  cp -p -f lisp/PSL.lisp lisp/PSL-save.lisp
 else
-  echo "Note: No previous PSL lisp file."
+  echo "Note: No previous specware lisp file."
 fi
 echo " "
 if [ -f bin/linux/PSL.dxl ]; then
-  echo "Saving previous PSL image ..."
-  echo "cp -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl"
-  cp -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl
+  echo "Saving previous specware image ..."
+  echo "cp -p -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl"
+  cp -p -f bin/linux/PSL.dxl bin/linux/PSL-save.dxl
 else
-  echo "Note: No previous PSL image."
+  echo "Note: No previous specware image."
 fi
 echo " "
 
@@ -70,8 +85,11 @@ echo " "
 # Is there a way to inhibit all the warnings (eg unused variable)
 # when Lisp loads?
 
-SWPATH=$SPECWARE4:.
-EXIT_ON_ERRORS=$SPECWARE4/Applications/Specware/bin/linux/exit-on-errors
+export SWPATH=$SPECWARE4:.
+EXIT_ON_ERRORS="$SPECWARE4"/Applications/Handwritten/Lisp/exit-on-errors
+MEMORY_MANAGEMENT="$SPECWARE4"/Applications/Handwritten/Lisp/memory-management
+
+echo "\$SWPATH=$SWPATH"
 
 # All the toplevel routines that activate Specware return a boolean value.
 # They return true if the call to Specware succeeded without activating
@@ -79,21 +97,27 @@ EXIT_ON_ERRORS=$SPECWARE4/Applications/Specware/bin/linux/exit-on-errors
 # handler is invoked. If, when bootrapping, the toplevel handler is
 # called, then we abort the bootstrap.
 
-echo "Bootstrapping from existing Specware image: bin/linux/Specware4.dxl"
-echo " "
-cd $SPECWARE4/Applications/Specware
-bin/linux/Specware4-text -batch <<-XXXX
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/PSL/lisp is not a directory" 2>&1
+   exit 1
+fi
+
+$SPECWARE4/Applications/Specware/bin/linux/Specware4-text -batch <<-XXXX
+	:swpath
 	(load "$EXIT_ON_ERRORS")
+	(load "$MEMORY_MANAGEMENT") 
+	(enlarge-stack)
 	(exiting-on-errors 
 	  (if (sw "/Applications/PSL/PSL")
 	    (exit 0)
 	    (exit 1)))
-	XXXX
+XXXX
 RC=$?
+
 # If the bootstrap failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "Bootstrap of PSL failed with code $RC, exiting ..."
+  echo "Bootstrap failed with code $RC, exiting ..."
   exit $RC
 fi
 
@@ -120,7 +144,7 @@ RC=$?
 # If the load failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "First load of PSL failed with code $RC, exiting ..."
+  echo "First load failed with code $RC, exiting ..."
   exit $RC
 fi
 
@@ -133,13 +157,25 @@ fi
 # People who want to avoid lots of line breaks can set *DEFAULT-RIGHT-MARGIN* 
 # in their lisp init.
 
+# big-alisp.dxl will have a larger lisp heap than the default alisp image.
+# Rebuild it each time.  A bit redundant, but ensures compatibility with 6.1/6.2/etc.
+BIG_ALISP="${SPECWARE4}/Applications/PSL/bin/linux/big-alisp.dxl"
+$LISP -batch <<-XXXX
+	(build-lisp-image "$BIG_ALISP" :lisp-heap-start #x48000000 :oldspace #x100)
+XXXX
+
 echo " "
 echo "Loading PSL ... (for dumplisp)"
 echo " "
-$LISP -batch <<-XXXX
+$LISP -I ${BIG_ALISP} -batch <<-XXXX
 	(load "$EXIT_ON_ERRORS")
+	(load "$MEMORY_MANAGEMENT") 
+	(compact-memory t)
+	(set-gc-parameters-for-build t)
 	(exiting-on-errors 
 	  (load "PSL.lisp"))
+	(compact-memory t 2 32000000)
+	(set-gc-parameters-for-use t)
 	(excl::dumplisp :name "$SPECWARE4/Applications/PSL/bin/linux/PSL.dxl")
 XXXX
 RC=$?
@@ -147,6 +183,6 @@ RC=$?
 # If the load failed (non-zero exit status) then we abort.
 if [ $RC -ne 0 ]; then
   echo ""
-  echo "Second load of PSL failed with code $RC, exiting ..."
+  echo "Second load failed with code $RC, exiting ..."
   exit $RC
 fi
diff --git a/Applications/Specware/bin/linux/bootstrap b/Applications/Specware/bin/linux/bootstrap
--- a/Applications/Specware/bin/linux/bootstrap
+++ b/Applications/Specware/bin/linux/bootstrap
@@ -4,70 +4,274 @@
 # That is,
 #  - it saves the old generated Specware4.lisp and Specware4.dxl (ie world)
 #  - it starts Specware4 
-#      - it first tries to run an existing image
+#      - it first tries to run a lisp session with an existing dxl image
 #      - if that fails it tries to load Specware from previously generated lisp
 #  - applies Specware to itself (sw "/Applications/Specware/Specware4")
 #     to generate a new Specware4.lisp,
-#  - starts a fresh lisp image,
+#  - starts a fresh lisp session
+#  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
+#    (this compiles everything)
+#  - starts a fresh lisp session again
 #  - loads the new Specware (under Handwritten/Lisp, (load "Specware4.lisp"))
 #  - dumps a world into the bin directory
 
 # Perhaps there should be a different script for bootstrapping from lisp
-# (bootstrap-from-lisp?.
+# (bootstrap-from-lisp?).
 
 # The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
 # files. See "man bash" for details. The 'set -v' turns on echoing of
 # lines read. This will be removed later.
 
-# Is there a way to inhibit all the warnings (eg unused variable)
-# when Lisp loads?
-
-set -v
-
-# We assume SPECWARE4 has been set.
+act='bootstrap'
 
 PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin
 
-LISP=${LISP:-/usr/local/acl/acl61/alisp}
+# set -v
 
-cd $SPECWARE4/Applications/Specware
+# Test whether SPECWARE4 has been set
+if [ -z "$SPECWARE4" ]; then
+    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
+    exit 1
+fi
 
-cp -f lisp/Specware4.lisp lisp/Specware4-save.lisp
-cp -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl
+# Test whether SPECWARE4 is a directory
+if [ ! -d "$SPECWARE4" ]; then
+   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
+   exit 1
+fi
+
+# Ensure SPECWARE4 is set to full pathname:
+case "$SPECWARE4" in
+    /*) : ok;;
+    *)  SPECWARE="`pwd`/$SPECWARE4";;
+esac
+
+if [ ! -d "$SPECWARE4"/Applications/Specware ]; then
+   echo "Failed to $act: could not find directory $SPECWARE4/Applications/Specware" 2>&1
+   exit 1
+fi
+
+echo cd "$SPECWARE4"/Applications/Specware
+cd "$SPECWARE4"/Applications/Specware
+
+# Try to find lisp executable:
+
+if [ -z "$LISP" ]; then
+   for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp; do
+      if [ -x "$L" ]; then
+         export LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
+
+echo " "
+if [ -f lisp/Specware4.lisp ]; then
+  echo "Saving previous specware lisp file ..."
+  echo "cp -p -f lisp/Specware4.lisp lisp/Specware4-save.lisp"
+  cp -p -f lisp/Specware4.lisp lisp/Specware4-save.lisp
+else
+  echo "Note: No previous specware lisp file."
+fi
+echo " "
+if [ -f bin/linux/Specware4.dxl ]; then
+  echo "Saving previous specware image ..."
+  echo "cp -p -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl"
+  cp -p -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl
+else
+  echo "Note: No previous specware image."
+fi
+echo " "
 
 # Note the use of the <<-XXXX in the following. The - means that preceeding
 # tabs are removed.  Thus the tabs that follow are significant. If you
 # change them to spaces, the end of the "here-document" is not recognized
 # (the XXXX).
 
-SWPATH=$SPECWARE4:.
+# Is there a way to inhibit all the warnings (eg unused variable)
+# when Lisp loads?
 
-if [ -f bin/linux/Specware4.dxl ]; then
-	echo Bootstrapping from existing Specware image 
-	bin/linux/Specware4-text <<-XXXX
-		(sw "/Applications/Specware/Specware4")
+export SWPATH="$SPECWARE4":.
+EXIT_ON_ERRORS="$SPECWARE4"/Applications/Handwritten/Lisp/exit-on-errors
+MEMORY_MANAGEMENT="$SPECWARE4"/Applications/Handwritten/Lisp/memory-management
+
+echo "\$SWPATH=$SWPATH"
+
+# All the toplevel routines that activate Specware return a boolean value.
+# They return true if the call to Specware succeeded without activating
+# Specware's toplevel handler. They return false (lisp nil) when the
+# handler is invoked. If, when bootrapping, the toplevel handler is
+# called, then we abort the bootstrap.
+
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/Specware/lisp is not a directory" 2>&1
+   exit 1
+fi
+
+
+if [   -f bin/linux/Specware4.dxl \
+     -a \(   \( ! -f Specware4-base.lisp \) \
+         -o bin/linux/Specware4.dxl -nt Specware4-base.lisp \) ]; then
+	echo "Bootstrapping from existing Specware image: bin/linux/Specware4.dxl"
+        echo " "
+	bin/linux/Specware4-text -batch <<-XXXX
+                :swpath
+		(load "$EXIT_ON_ERRORS")    
+		(load "$MEMORY_MANAGEMENT") 
+		(enlarge-stack)
+		(exiting-on-errors 
+		  (if (sw "/Applications/Specware/Specware4")
+		    (exit 0)
+		    (exit 11)))
 	XXXX
+        RC=$?
 else
-	if [ -f lisp/Specware4.lisp ]; then
-		echo Bootstrapping from previously generated lisp
-		$LISP <<-XXXX
-			cd Handwritten/Lisp
-			(load "Specware4.lisp")
-			(sw "/Applications/Specware/Specware4")
+        if [   -f lisp/Specware4.lisp \
+	     -a \(    \( ! -f Specware4-base.lisp \) \
+                 -o lisp/Specware4.lisp -nt Specware4-base.lisp \) ]; then
+		if [ -f bin/linux/Specware4.dxl ]; then
+  		    echo "Cvs saved lisp, Specware4-base.lisp, is newer than bin/linux/Specware4.dxl."
+		fi
+		echo "Bootstrapping from previously generated lisp: lisp/Specware4.lisp"
+                echo " "
+		cd Handwritten/Lisp
+		$LISP -batch <<-XXXX
+			(load "$EXIT_ON_ERRORS")
+		        (load "$MEMORY_MANAGEMENT") 
+			(enlarge-stack)
+			(exiting-on-errors 
+			  (load "Specware4.lisp")
+			  (if (sw "/Applications/Specware/Specware4")
+			    (exit 0)
+			    (exit 22)))
 		XXXX
+                RC=$?
 	else
-		echo "Bootstrap failed"
-		echo "Could not find bin/linux/Specware4.dxl or lisp/Specware4.lisp"
-		exit 1
+                if [ -f Specware4-base.lisp ]; then
+			if [ -f bin/linux/Specware4.dxl ]; then
+			    echo "Cvs saved lisp, Specware4-base.lisp, is newer than bin/linux/Specware4.dxl."
+			fi
+			if [ -f lisp/Specware4.lisp ]; then
+			    echo "Cvs saved lisp, Specware4-base.lisp, is newer than both lisp/Specware4.lisp."
+			fi
+                        echo "Bootstrapping from cvs saved lisp: Specware4-base.lisp"
+			if [ ! -d lisp ]; then
+			    echo "mkdir lisp"
+			    mkdir lisp
+			fi
+
+			echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
+			cp -p -f Specware4-base.lisp lisp/Specware4.lisp
+			echo " "
+			cd Handwritten/Lisp
+			$LISP -batch <<-XXXX
+			    (load "$EXIT_ON_ERRORS")
+		            (load "$MEMORY_MANAGEMENT") 
+			    (enlarge-stack)
+			    (exiting-on-errors 
+			      (load "Specware4.lisp")
+			      (if (sw "/Applications/Specware/Specware4")
+				(exit 0)
+			        (exit 33)))
+			XXXX
+			RC=$?
+		else
+		    # You should never end up here.
+		    # If you do then cvs checkout/update did not correctly
+		    # provide you with a Specware4-base.lisp.
+		    echo " "
+		    echo "Bootstrap failed"
+		    echo "Could not find bin/linux/Specware4.dxl or lisp/Specware4.lisp or Specware4-base.lisp"
+		    echo "under $SPECWARE4/Applications/Specware"
+		    exit 1
+		fi
 	fi
 fi
 
-cd $SPECWARE4/Applications/Specware/Handwritten/Lisp
+# If the bootstrap failed (non-zero exit status) then we abort.
+if [ $RC -ne 0 ]; then
+  echo ""
+  echo "Bootstrap failed with code $RC, exiting ..."
+  exit $RC
+fi
 
-# I don't know what setting *DEFAULT-RIGHT-MARGIN* does. Can someone explain?
+echo " "
+echo cd "$SPECWARE4"/Applications/Specware/Handwritten/Lisp
+cd "$SPECWARE4"/Applications/Specware/Handwritten/Lisp
 
-$LISP <<-XXXX
-	(load "Specware4.lisp")
-	(let (#+ALLEGRO (EXCL::*DEFAULT-RIGHT-MARGIN* 1000))
-	(excl::dumplisp :name "$SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl"))
+# We load the new Specware4.lisp twice, each in a fresh lisp session. The
+# first time compiles everything.  As we have just generated a new
+# lisp file for Specware, we are certain something needs to be compiled.
+# We could do the load and compile up above in the lisp that generated it,
+# but that seems weird to me ...
+
+echo " "
+echo "Loading Specware ... (to compile)"
+echo " "
+$LISP -batch <<-XXXX
+	(load "$EXIT_ON_ERRORS")
+	(exiting-on-errors 
+	  (load "Specware4.lisp"))
 XXXX
+RC=$?
+
+# If the load failed (non-zero exit status) then we abort.
+if [ $RC -ne 0 ]; then
+  echo ""
+  echo "First load failed with code $RC, exiting ..."
+  exit $RC
+fi
+
+# The second time is just to do the dumplisp. If we do it in one
+# go, the generated dxl file is almost 4 times larger.
+#
+# I once added a (gc) between the load and the dumplisp, and the dxl
+# file became 10k bigger. Go figure.
+
+# People who want to avoid lots of line breaks can set *DEFAULT-RIGHT-MARGIN* 
+# in their lisp init.
+
+# big-alisp.dxl will have a larger lisp heap than the default alisp image.
+# Rebuild it each time.  A bit redundant, but ensures compatibility with 6.1/6.2/etc.
+BIG_ALISP="${SPECWARE4}/Applications/Specware/bin/linux/big-alisp.dxl"
+$LISP -batch <<-XXXX
+	(build-lisp-image "$BIG_ALISP" :lisp-heap-start #x48000000 :oldspace #x100)
+XXXX
+
+echo " "
+echo "Loading Specware ... (for dumplisp)"
+echo " "
+$LISP -I ${BIG_ALISP} -batch <<-XXXX
+	(load "$EXIT_ON_ERRORS")
+	(load "$MEMORY_MANAGEMENT") 
+	(compact-memory t 0 32000000)
+	(set-gc-parameters-for-build t)
+	(exiting-on-errors 
+	  (load "Specware4.lisp"))
+	(compact-memory t -1 0)
+	(set-gc-parameters-for-use t)
+        (excl::dumplisp :name "$SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl")
+XXXX
+RC=$?
+
+# If the load failed (non-zero exit status) then we abort.
+if [ $RC -ne 0 ]; then
+  echo ""
+  echo "Second load failed with code $RC, exiting ..."
+  exit $RC
+fi
+
+cd "$SPECWARE4"/Applications/Specware/lisp
+if cmp -s Specware4.lisp Specware4-save.lisp; then
+  echo " "
+  echo "The bootstrap reached a fixed point"
+fi
diff --git a/Applications/Specware/bin/linux/build-image b/Applications/Specware/bin/linux/build-image
--- a/Applications/Specware/bin/linux/build-image
+++ b/Applications/Specware/bin/linux/build-image
@@ -7,36 +7,142 @@
 # files. See man bash for details. The 'set -v' turns on echoing of
 # lines read. this will be removed later.
 
-set -v
-
-# We assume SPECWARE4 has been set.
-
-if [ -z $SPECWARE4 ]; then
-	echo "Failed to build image, SPECWARE4 environment variable not set"
-	exit 1
-fi
+act='build image'
 
 PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin
 
-LISP=${LISP:-/usr/local/acl/acl61/alisp}
+set -v
 
-cd $SPECWARE4/Applications/Specware
+# Test whether SPECWARE4 has been set
 
-SWPATH=$SPECWARE4:.
+if [ -z "$SPECWARE4" ]; then
+    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
+    exit 1
+fi
 
-if [ ! -f lisp/Specware4.lisp ] ; then
-	echo "Failed to build image: could not find $SPECWARE4/Applications/Specware/lisp/Specware4.lisp"
-	exit 1
+# Test whether SPECWARE4 is a directory
+
+if [ ! -d "$SPECWARE4" ]; then
+   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
+   exit 1
+fi
+
+# Ensure SPECWARE4 is set to full pathname:
+
+case "$SPECWARE" in
+    /*) : ok;;
+    *)  SPECWARE="`pwd`/$SPECWARE";;
+esac
+
+# Try to find lisp executable:
+
+if [ -z "$LISP" ]; then
+   for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp; do
+      if [ -x "$L" ]; then
+         LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
+
+if [ ! -d "$SPECWARE4"/Applications/Specware ]; then
+   echo "Failed to $act: could not find directory
+   $SPECWARE4/Applications/Specware" 2>&1
+   exit 1
+fi
+
+cd "$SPECWARE4"/Applications/Specware
+
+export SWPATH; SWPATH="$SPECWARE4":.
+EXIT_ON_ERRORS="$SPECWARE4"/Applications/Handwritten/Lisp/exit-on-errors
+MEMORY_MANAGEMENT="$SPECWARE4"/Applications/Handwritten/Lisp/memory-management
+
+if [ -f lisp ]; then
+   echo "Failed to $act, $SPECWARE4/Applications/Specware/lisp is not a directory" 2>&1
+   exit 1
+fi
+
+
+if [ ! -f lisp/Specware4.lisp -a ! -f Specware4-base.lisp ] ; then
+   echo "Failed to $act: could not find $SPECWARE4/Applications/Specware/lisp/Specware4.lisp
+   or $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+   exit 1
+fi
+
+if [ ! -f lisp/Specware4.lisp ]; then
+    echo "Could not find $SPECWARE4/Applications/Specware/lisp/Specware4.lisp,
+    using cvs saved lisp, $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+    if [ ! -d lisp ]; then
+	echo "mkdir lisp"
+	mkdir lisp
+    fi
+    echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
+    cp -p -f Specware4-base.lisp lisp/Specware4.lisp
+fi
+
+if [ Specware4-base.lisp -nt lisp/Specware4.lisp ]; then
+    echo "$SPECWARE4/Applications/Specware/lisp/Specware4.lisp is older than
+    cvs saved lisp, $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+    echo "Using $SPECWARE4/Applications/Specware/Specware4-base.lisp" 2>&1
+    if [ ! -d lisp ]; then
+	echo "mkdir lisp"
+	mkdir lisp
+    fi
+    echo "cp -p -f Specware4-base.lisp lisp/Specware4.lisp"
+    cp -p -f Specware4-base.lisp lisp/Specware4.lisp
 fi
 
 cp -f bin/linux/Specware4.dxl bin/linux/Specware4-save.dxl
 
 cd Handwritten/Lisp
 
-# I don't know what setting *DEFAULT-RIGHT-MARGIN* does. Can someone explain?
-
+# We load the new Specware4.lisp twice, each in a fresh lisp session. The
+# first time compiles everything.  This may not be necessary but it is
+# easier just to load it twice rather than to try to figure out if something
+# needs to be compiled.
 $LISP <<-XXXX
-	(load "Specware4.lisp")
-	(let (#+ALLEGRO (EXCL::*DEFAULT-RIGHT-MARGIN* 1000))
-	(excl::dumplisp :name "$SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl"))
+	(load "$EXIT_ON_ERRORS")
+	(exiting-on-errors 
+	  (load "Specware4.lisp"))
+XXXX
+
+# The second time is just to do the dumplisp. If we do it in one go,
+# and something needs compiling, the generated dxl file is almost 4
+# times larger.
+#
+# I once added a (gc) between the load and the dumplisp, and the dxl
+# file became 10k bigger. Go figure.
+#
+# I don't know what setting *DEFAULT-RIGHT-MARGIN* does. Can someone explain?
+# Do we need it here?
+
+# big-alisp.dxl will have a larger lisp heap than the default alisp image.
+# Rebuild it each time.  A bit redundant, but ensures compatibility with 6.1/6.2/etc.
+BIG_ALISP="${SPECWARE4}/Applications/Specware/bin/linux/big-alisp.dxl"
+$LISP -batch <<-XXXX
+	(build-lisp-image "$BIG_ALISP" :lisp-heap-start #x48000000 :oldspace #x100)
+XXXX
+
+echo " "
+echo "Loading Specware ... (for dumplisp)"
+echo " "
+$LISP -I ${BIG_ALISP} -batch <<-XXXX
+	(load "$EXIT_ON_ERRORS")
+	(load "$MEMORY_MANAGEMENT") 
+	(compact-memory t 0 32000000)
+	(set-gc-parameters-for-build t)
+	(exiting-on-errors 
+	  (load "Specware4.lisp"))
+	(compact-memory t -1 0)
+	(set-gc-parameters-for-use t)
+	(excl::dumplisp :name "$SPECWARE4/Applications/Specware/bin/linux/Specware4.dxl")
 XXXX
