Bash scripts to start Specware in cygwin
git-svn-id: svn+ssh://svn.kestrel.edu/Specware/trunk@6029 7b97033b-253e-4a5c-9b07-e25f9089a9fd

diff --git a/Applications/Specware/bin/windows/XEmacs_Specware b/Applications/Specware/bin/windows/XEmacs_Specware
--- a/Applications/Specware/bin/windows/XEmacs_Specware
+++ b/Applications/Specware/bin/windows/XEmacs_Specware
@@ -1,14 +1,11 @@
-#!/bin/sh
+#!/bin/bash --noprofile
 (shopt -s igncr) 2>/dev/null && shopt -s igncr;  # Ignore cr's
 
-LISP_MODE=SBCL
+# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
+# files. See "man bash" for details. 
 
-# $HOME/Specware4/Library/Base/older
-
-xemacs=`which xemacs`
 act='launch Specware'
 
-OLDPATH=$PATH
 PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:${PATH}
 
 # Test whether SPECWARE4 has been set
@@ -26,29 +23,31 @@ if [ ! -d "$SPECWARE4" ]; then
 fi
 
 # Ensure SPECWARE4 is set to full pathname:
-case "$SPECWARE" in
+
+case "$SPECWARE4" in
     /*) : ok;;
-    *)  SPECWARE="`pwd`/$SPECWARE";;
+    *)  SPECWARE4="`pwd`/$SPECWARE4";;
 esac
 
-echo "\$SPECWARE4=$SPECWARE4"
-
 # Test whether SPECWARE4 has been set
+
 if [ -z "$SPECWARE4" ]; then
     echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
     exit 1
 fi
 
 # Test whether SPECWARE4 is a directory
+
 if [ ! -d "$SPECWARE4" ]; then
    echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
    exit 1
 fi
 
 # Ensure SPECWARE4 is set to full pathname:
-case "$SPECWARE" in
+
+case "$SPECWARE4" in
     /*) : ok;;
-    *)  SPECWARE="`pwd`/$SPECWARE";;
+    *)  SPECWARE4="`pwd`/$SPECWARE4";;
 esac
 
 if [ ! -d "$SPECWARE4"/Applications/Specware ]; then
@@ -59,23 +58,37 @@ fi
 
 SPECWARE_BIN="$SPECWARE4"/Applications/Specware/bin/windows
 
+# Ensure SWPATH is set
 
 if [ -z "$SWPATH" ]; then
   SWPATH="C:/cygwin;/"
   export SWPATH
 fi
 
+# Try to find lisp executable:
+
+if [ -z "$LISP" ]; then
+   for L in /Applications/sbcl/bin/sbcl /usr/local/bin/sbcl "$HOME"/bin/sbcl /bin/lisp; do
+      if [ -x "$L" ]; then
+         LISP="$L"; break
+      fi
+   done
+fi
+
+if [ -z "$LISP" ]; then
+   echo "Failed to $act, no LISP executable found" 2>&1
+   exit 1
+fi
+
+if [ ! -x "$LISP" ]; then
+   echo "Failed to $act, $LISP is not executable" 2>&1
+   exit 1
+fi
 
 if [ -z "$SPECWARE_INIT_FORM" ]; then
    SPECWARE_INIT_FORM=NIL
    export SPECWARE_INIT_FORM
 fi
-
-# Try to find lisp executable:
-
-BIN_DIR=$SPECWARE_BIN
-
-#. $SPECWARE4/Scripts/unix/Verify_$LISP_MODE
 
 LISP_DIR=`dirname "$LISP"`
 LISP_EXECUTABLE="$SPECWARE_BIN"/Specware4.exe
@@ -85,6 +98,7 @@ export LISP_EXECUTABLE
 export LISP_HEAP_IMAGE
 export LISP_DIRECTORY
 
-PATH=$OLDPATH
-$xemacs -l "$SPECWARE4"/Library/IO/Emacs/load-slime $* -f run-specware4 &
+# Load specware emacs files, do command line options (e.g. load and
+# start Isabelle and then run-specware4
 
+xemacs -l $SPECWARE4/Library/IO/Emacs/load-slime.el $* -f run-specware4&
